### ISSUE TITLE
:sparkles: Implement the Reception

### ISSUE THREAD

**Issue by Thomaltarix** [Peralban/Plazza#12]
# :white_check_mark: What's needed
You must implement a class badly named `Reception`.
This class has to communicate with the shell class to get data and process using it.

## 📋 Subtasks
This class needs have methods that:
- [x] Implement Messages Queue IPC
- [ ] Catch data from the shell class and store it
- [ ] Allocate pizzas to existing Kitchens (pizza by pizza)
- [ ] Balance the kitchens (a reception with a kitchen with 50 000 pizzas and another with 1 pizza is not balanced)
- [ ] Create another kitchen if all are already full

## :file_folder: Files required
- [ ] `src/Reception.cpp`
- [ ] `src/Reception.hpp`
