### ISSUE TITLE
:bar_chart: implement "status" command

### ISSUE THREAD

**Issue by landryarki** [Peralban/Plazza#13]
# :white_check_mark: What's needed
the shell must have a status command to displays the kitchens status, including the current occupancy of the cooks, as well as theirs stocks of ingredients

## 📋 Subtasks
- [x] catch token status
- [x] send to all kitchens the status command
- [x] display in an elegant format
